apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: job-ubuntu-network-policy
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: job-ubuntu
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.0.0/16
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 172.16.0.0/12
